package marcel.demonworld.armygenerator.mapperImplementations;

import marcel.demonworld.armygenerator.dto.game.EntityDTOs.UnitCardDTO;
import marcel.demonworld.armygenerator.dto.game.WrapperDTOs.EquipmentTypes;
import marcel.demonworld.armygenerator.entities.UnitCard;
import marcel.demonworld.armygenerator.mappingInterfaces.UnitCardMapper;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

import java.util.Collections;


@Component
@Primary
public class unitCardMapperImplementation implements UnitCardMapper {


    @Override
    public UnitCardDTO entityToDto(UnitCard unitCard) {
        return UnitCardDTO.builder()
                .armourMelee(unitCard.getArmourMelee())
                .armourRange(unitCard.getArmourRange())
                .belongsToUnit(unitCard.getBelongsToUnit())
                .charge(unitCard.getCharge())
                .chargeBonus(unitCard.getChargeBonus())
                .commandStars(unitCard.getCommandStars())
                .controlZone(unitCard.getControlZone())
                //  The table unis does not have these fields. So it initialized here as an empty list.
                .equipment(Collections.emptyList())
                .equipmentTypes(new EquipmentTypes())
                .faction(unitCard.getFaction())
                .fear(unitCard.getFear())
                .hasShield(unitCard.getHasShield())
                .hitpoints(unitCard.getHitpoints())
                .hold_maneuvers(unitCard.getHold_maneuvers())
                .horde(unitCard.getHorde())
                .Id(unitCard.getId())
                .initiative(unitCard.getInitiative())
                .isHighFlyer(unitCard.getIsHighFlyer())
                .isLowFlyer(unitCard.getIsLowFlyer())
                .isMultiStateUnit(unitCard.getIsMultiStateUnit())
                .isMounted(unitCard.getIsMounted())
                .leader(unitCard.getLeader())
                .leaderIsClosedOrder(unitCard.getLeaderIsClosedOrder())
                .magic(unitCard.getMagic())
                .maxFieldsMove(unitCard.getMaxFieldsMove())
                .move(unitCard.getMove())
                .moral1(unitCard.getMoral1())
                .moral2(unitCard.getMoral2())
                .multiCardName(unitCard.getMultiCardName())
                .multiStateOrderNumber(unitCard.getMultiStateOrderNumber())
                .isMultiStateUnit(unitCard.getIsMultiStateUnit())
                .multiCardName(unitCard.getMultiCardName())
                .musician(unitCard.getMusician())
                .numberOfElements(unitCard.getNumberOfElements())
                .overRun(unitCard.getOverRun())
                .points(unitCard.getPoints())
                .rangedAttackStats(unitCard.getRangedAttackStats())
                .rangedWeapon(unitCard.getRangedWeapon())
                .secondSubFaction(unitCard.getSecondSubFaction())
                .skillMelee(unitCard.getSkillMelee())
                .skillRange(unitCard.getSkillRange())
                .skirmish(unitCard.getSkirmish())
                .skirmishFormation(unitCard.getSkirmishFormation())
                .specialRules(unitCard.getSpecialRules())
                .squareFormation(unitCard.getSquareFormation())
                .shieldWallFormation(unitCard.getShieldWallFormation())
                .standardBearer(unitCard.getStandardBearer())
                .subFaction(unitCard.getSubFaction())
                .unitName(unitCard.getUnitName())
                .unitSize(unitCard.getUnitSize())
                .unitType(unitCard.getUnitType())
                .uniqueUnit(unitCard.getUniqueUnit())
                .unitIsClosedOrder(unitCard.getUnitIsClosedOrder())
                .weapon1(unitCard.getWeapon1())
                .weapon1Name(unitCard.getWeapon1Name())
                .weapon2(unitCard.getWeapon2())
                .weapon2Name(unitCard.getWeapon2Name())
                .weapon3(unitCard.getWeapon3())
                .weapon3Name(unitCard.getWeapon3Name())
                .wedgeFormation(unitCard.getWedgeFormation())
                .isCustom(unitCard.getIsCustom())
                .createdBy(unitCard.getCreatedBy())
                .isDeleted(unitCard.getIsDeleted())
                .isEligibleFor2ndSubFaction(unitCard.getIsEligibleFor2ndSubFaction())
                .build();


    }

    @Override
    public UnitCard dtoToEntity(UnitCardDTO unitCardDTO) {
        return UnitCard.builder()
                .armourMelee(unitCardDTO.getArmourMelee())
                .armourRange(unitCardDTO.getArmourRange())
                .belongsToUnit(unitCardDTO.getBelongsToUnit())
                .charge(unitCardDTO.getCharge())
                .chargeBonus(unitCardDTO.getChargeBonus())
                .commandStars(unitCardDTO.getCommandStars())
                .controlZone(unitCardDTO.getControlZone())
                .faction(unitCardDTO.getFaction())
                .fear(unitCardDTO.getFear())
                .hasShield(unitCardDTO.getHasShield())
                .hitpoints(unitCardDTO.getHitpoints())
                .hold_maneuvers(unitCardDTO.getHold_maneuvers())
                .horde(unitCardDTO.getHorde())
                .initiative(unitCardDTO.getInitiative())
                .isHighFlyer(unitCardDTO.getIsHighFlyer())
                .isLowFlyer(unitCardDTO.getIsLowFlyer())
                .isMultiStateUnit(unitCardDTO.getIsMultiStateUnit())
                .isMounted(unitCardDTO.getIsMounted())
                .leader(unitCardDTO.getLeader())
                .leaderIsClosedOrder(unitCardDTO.getLeaderIsClosedOrder())
                .magic(unitCardDTO.getMagic())
                .maxFieldsMove(unitCardDTO.getMaxFieldsMove())
                .move(unitCardDTO.getMove())
                .moral1(unitCardDTO.getMoral1())
                .moral2(unitCardDTO.getMoral2())
                .multiCardName(unitCardDTO.getMultiCardName())
                .multiStateOrderNumber(unitCardDTO.getMultiStateOrderNumber())
                .isMultiStateUnit(unitCardDTO.getIsMultiStateUnit())
                .multiCardName(unitCardDTO.getMultiCardName())
                .musician(unitCardDTO.getMusician())
                .numberOfElements(unitCardDTO.getNumberOfElements())
                .overRun(unitCardDTO.getOverRun())
                .points(unitCardDTO.getPoints())
                .rangedAttackStats(unitCardDTO.getRangedAttackStats())
                .rangedWeapon(unitCardDTO.getRangedWeapon())
                .secondSubFaction(unitCardDTO.getSecondSubFaction())
                .skillMelee(unitCardDTO.getSkillMelee())
                .skillRange(unitCardDTO.getSkillRange())
                .skirmish(unitCardDTO.getSkirmish())
                .skirmishFormation(unitCardDTO.getSkirmishFormation())
                .specialRules(unitCardDTO.getSpecialRules())
                .squareFormation(unitCardDTO.getSquareFormation())
                .shieldWallFormation(unitCardDTO.getShieldWallFormation())
                .standardBearer(unitCardDTO.getStandardBearer())
                .subFaction(unitCardDTO.getSubFaction())
                .unitName(unitCardDTO.getUnitName())
                .unitSize(unitCardDTO.getUnitSize())
                .unitType(unitCardDTO.getUnitType())
                .uniqueUnit(unitCardDTO.getUniqueUnit())
                .unitIsClosedOrder(unitCardDTO.getUnitIsClosedOrder())
                .weapon1(unitCardDTO.getWeapon1())
                .weapon1Name(unitCardDTO.getWeapon1Name())
                .weapon2(unitCardDTO.getWeapon2())
                .weapon2Name(unitCardDTO.getWeapon2Name())
                .weapon3(unitCardDTO.getWeapon3())
                .weapon3Name(unitCardDTO.getWeapon3Name())
                .wedgeFormation(unitCardDTO.getWedgeFormation())
                .isCustom(unitCardDTO.getIsCustom())
                .createdBy(unitCardDTO.getCreatedBy())
                .isDeleted(unitCardDTO.getIsDeleted())
                .isEligibleFor2ndSubFaction(unitCardDTO.getIsEligibleFor2ndSubFaction())
                .build();
    }
}
